# Generated by Django 5.0.4 on 2024-05-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=35)),
                ('telefono', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
