# Generated by Django 5.0.4 on 2024-05-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
