# Generated by Django 5.0.4 on 2024-05-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombreEmpresa',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
