# Generated by Django 5.0.4 on 2024-06-02 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0004_alter_cliente_avatar_alter_cliente_bio_and_more'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoServicio', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicioConsultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('duracion', models.IntegerField()),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('consultoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultoria.consultoria')),
                ('empleadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
        ),
    ]
