# Generated by Django 5.0.4 on 2024-06-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioconsultoria',
            name='fechaFin',
            field=models.DateField(null=True),
        ),
    ]
