# Generated by Django 5.0.4 on 2024-06-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultoria', '0002_servicioconsultoria_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioconsultoria',
            name='fechaInicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
