# Generated by Django 5.0.4 on 2024-06-03 01:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0005_alter_direccion_cliente'),
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('P', 'pending'), ('PR', 'processing'), ('A', 'approved'), ('R', 'rejected'), ('F', 'failed')], default='P', max_length=2)),
                ('divisa', models.CharField(default='COP', editable=False, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('direccion_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion_envio', to='cliente.direccion')),
                ('direccion_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion_pago', to='cliente.direccion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo_venta', to='equipo.equipo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_items', to='venta.venta')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
