# Generated by Django 5.0.4 on 2024-06-02 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_avatar_alter_cliente_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
